language: csharp

mono:
 - 4.4.1

os:
 - osx
 - linux

env:
 - TRAVIS_OS_UNAME=$(uname -s)

solution: libsodium-net.sln

install:
 - nuget restore libsodium-net.sln
 - nuget install NUnit.ConsoleRunner -Version 3.6.1 -OutputDirectory testrunner

before_script:
 - bash travis-build-libsodium.sh

script:
 - xbuild libsodium-net.sln
 - mono ./testrunner/NUnit.ConsoleRunner.3.6.1/tools/nunit3-console.exe ./Tests/bin/Debug/Tests.dll
